//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Percentage.App.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Percentage.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string About_AppInfo {
            get { return ResourceManager.GetString("About_AppInfo", resourceCulture); }
        }

        public static string About_CopyErrorTooltip {
            get { return ResourceManager.GetString("About_CopyErrorTooltip", resourceCulture); }
        }

        public static string About_ErrorLinkText {
            get { return ResourceManager.GetString("About_ErrorLinkText", resourceCulture); }
        }

        public static string About_ErrorMessageBefore {
            get { return ResourceManager.GetString("About_ErrorMessageBefore", resourceCulture); }
        }

        public static string About_ErrorTitle {
            get { return ResourceManager.GetString("About_ErrorTitle", resourceCulture); }
        }

        public static string About_LinkGitHub {
            get { return ResourceManager.GetString("About_LinkGitHub", resourceCulture); }
        }

        public static string About_LinkPayPal {
            get { return ResourceManager.GetString("About_LinkPayPal", resourceCulture); }
        }

        public static string About_RateApp {
            get { return ResourceManager.GetString("About_RateApp", resourceCulture); }
        }

        public static string About_ReportIssue {
            get { return ResourceManager.GetString("About_ReportIssue", resourceCulture); }
        }

        public static string About_SourceCode {
            get { return ResourceManager.GetString("About_SourceCode", resourceCulture); }
        }

        public static string About_SupportMyWork {
            get { return ResourceManager.GetString("About_SupportMyWork", resourceCulture); }
        }

        public static string App_GeneralErrorBody {
            get { return ResourceManager.GetString("App_GeneralErrorBody", resourceCulture); }
        }

        public static string App_GeneralErrorTitle {
            get { return ResourceManager.GetString("App_GeneralErrorTitle", resourceCulture); }
        }

        public static string App_OutOfMemoryBody {
            get { return ResourceManager.GetString("App_OutOfMemoryBody", resourceCulture); }
        }

        public static string App_OutOfMemoryTitle {
            get { return ResourceManager.GetString("App_OutOfMemoryTitle", resourceCulture); }
        }

        public static string AppInfo_RuntimeArchitecture {
            get { return ResourceManager.GetString("AppInfo_RuntimeArchitecture", resourceCulture); }
        }

        public static string AppInfo_RuntimeVersion {
            get { return ResourceManager.GetString("AppInfo_RuntimeVersion", resourceCulture); }
        }

        public static string AppInfo_Version {
            get { return ResourceManager.GetString("AppInfo_Version", resourceCulture); }
        }

        public static string Battery_Capacity {
            get { return ResourceManager.GetString("Battery_Capacity", resourceCulture); }
        }

        public static string Battery_ChargeRate {
            get { return ResourceManager.GetString("Battery_ChargeRate", resourceCulture); }
        }

        public static string Battery_DesignCapacity {
            get { return ResourceManager.GetString("Battery_DesignCapacity", resourceCulture); }
        }

        public static string Battery_FullChargeCapacity {
            get { return ResourceManager.GetString("Battery_FullChargeCapacity", resourceCulture); }
        }

        public static string Battery_Health {
            get { return ResourceManager.GetString("Battery_Health", resourceCulture); }
        }

        public static string Battery_PowerLineStatus {
            get { return ResourceManager.GetString("Battery_PowerLineStatus", resourceCulture); }
        }

        public static string Battery_RemainingChargeCapacity {
            get { return ResourceManager.GetString("Battery_RemainingChargeCapacity", resourceCulture); }
        }

        public static string Battery_Status {
            get { return ResourceManager.GetString("Battery_Status", resourceCulture); }
        }

        public static string Battery_Time {
            get { return ResourceManager.GetString("Battery_Time", resourceCulture); }
        }

        public static string Battery_TimeRemaining {
            get { return ResourceManager.GetString("Battery_TimeRemaining", resourceCulture); }
        }

        public static string Battery_TimeUntilFull {
            get { return ResourceManager.GetString("Battery_TimeUntilFull", resourceCulture); }
        }

        public static string Battery_ValueConnected {
            get { return ResourceManager.GetString("Battery_ValueConnected", resourceCulture); }
        }

        public static string Battery_ValueDisconnected {
            get { return ResourceManager.GetString("Battery_ValueDisconnected", resourceCulture); }
        }

        public static string Battery_ValueNotCharging {
            get { return ResourceManager.GetString("Battery_ValueNotCharging", resourceCulture); }
        }

        public static string Battery_ValueUnknown {
            get { return ResourceManager.GetString("Battery_ValueUnknown", resourceCulture); }
        }

        public static string Details_CopyButton {
            get { return ResourceManager.GetString("Details_CopyButton", resourceCulture); }
        }

        public static string Details_PageTitle {
            get { return ResourceManager.GetString("Details_PageTitle", resourceCulture); }
        }

        public static string Details_RefreshButton {
            get { return ResourceManager.GetString("Details_RefreshButton", resourceCulture); }
        }

        public static string Main_WindowTitle {
            get { return ResourceManager.GetString("Main_WindowTitle", resourceCulture); }
        }

        public static string Nav_About {
            get { return ResourceManager.GetString("Nav_About", resourceCulture); }
        }

        public static string Nav_Details {
            get { return ResourceManager.GetString("Nav_Details", resourceCulture); }
        }

        public static string Nav_Settings {
            get { return ResourceManager.GetString("Nav_Settings", resourceCulture); }
        }

        public static string Readable_HourPlural {
            get { return ResourceManager.GetString("Readable_HourPlural", resourceCulture); }
        }

        public static string Readable_HourSingular {
            get { return ResourceManager.GetString("Readable_HourSingular", resourceCulture); }
        }

        public static string Readable_LessThanOneMinute {
            get { return ResourceManager.GetString("Readable_LessThanOneMinute", resourceCulture); }
        }

        public static string Readable_MinutePlural {
            get { return ResourceManager.GetString("Readable_MinutePlural", resourceCulture); }
        }

        public static string Readable_MinuteSingular {
            get { return ResourceManager.GetString("Readable_MinuteSingular", resourceCulture); }
        }

        public static string Settings_AutoColour {
            get { return ResourceManager.GetString("Settings_AutoColour", resourceCulture); }
        }

        public static string Settings_AutoColourTooltip {
            get { return ResourceManager.GetString("Settings_AutoColourTooltip", resourceCulture); }
        }

        public static string Settings_AutoStart {
            get { return ResourceManager.GetString("Settings_AutoStart", resourceCulture); }
        }

        public static string Settings_AutoStartDescription {
            get { return ResourceManager.GetString("Settings_AutoStartDescription", resourceCulture); }
        }

        public static string Settings_AutoStartDisabledByPolicyDialogContent {
            get { return ResourceManager.GetString("Settings_AutoStartDisabledByPolicyDialogContent", resourceCulture); }
        }

        public static string Settings_AutoStartDisabledByPolicyDialogTitle {
            get { return ResourceManager.GetString("Settings_AutoStartDisabledByPolicyDialogTitle", resourceCulture); }
        }

        public static string Settings_AutoStartDisabledByUserDialogContent {
            get { return ResourceManager.GetString("Settings_AutoStartDisabledByUserDialogContent", resourceCulture); }
        }

        public static string Settings_AutoStartDisabledByUserDialogTitle {
            get { return ResourceManager.GetString("Settings_AutoStartDisabledByUserDialogTitle", resourceCulture); }
        }

        public static string Settings_AutoStartDisabledDialogContent {
            get { return ResourceManager.GetString("Settings_AutoStartDisabledDialogContent", resourceCulture); }
        }

        public static string Settings_AutoStartDisabledDialogTitle {
            get { return ResourceManager.GetString("Settings_AutoStartDisabledDialogTitle", resourceCulture); }
        }

        public static string Settings_AutoStartDisabledMessage {
            get { return ResourceManager.GetString("Settings_AutoStartDisabledMessage", resourceCulture); }
        }

        public static string Settings_AutoStartDisabledTitle {
            get { return ResourceManager.GetString("Settings_AutoStartDisabledTitle", resourceCulture); }
        }

        public static string Settings_BatteryLevelsAndNotifications {
            get { return ResourceManager.GetString("Settings_BatteryLevelsAndNotifications", resourceCulture); }
        }

        public static string Settings_BatteryLevelsAndNotificationsDescription {
            get { return ResourceManager.GetString("Settings_BatteryLevelsAndNotificationsDescription", resourceCulture); }
        }

        public static string Settings_DoubleClickActivation {
            get { return ResourceManager.GetString("Settings_DoubleClickActivation", resourceCulture); }
        }

        public static string Settings_DoubleClickActivationDescription {
            get { return ResourceManager.GetString("Settings_DoubleClickActivationDescription", resourceCulture); }
        }

        public static string Settings_FontSize {
            get { return ResourceManager.GetString("Settings_FontSize", resourceCulture); }
        }

        public static string Settings_HideAtStartup {
            get { return ResourceManager.GetString("Settings_HideAtStartup", resourceCulture); }
        }

        public static string Settings_HideAtStartupDescription {
            get { return ResourceManager.GetString("Settings_HideAtStartupDescription", resourceCulture); }
        }

        public static string Settings_LanguageDescription {
            get { return ResourceManager.GetString("Settings_LanguageDescription", resourceCulture); }
        }

        public static string Settings_LanguageHeader {
            get { return ResourceManager.GetString("Settings_LanguageHeader", resourceCulture); }
        }

        public static string Settings_LanguageSystem {
            get { return ResourceManager.GetString("Settings_LanguageSystem", resourceCulture); }
        }

        public static string Settings_LevelCharging {
            get { return ResourceManager.GetString("Settings_LevelCharging", resourceCulture); }
        }

        public static string Settings_LevelCritical {
            get { return ResourceManager.GetString("Settings_LevelCritical", resourceCulture); }
        }

        public static string Settings_LevelFull {
            get { return ResourceManager.GetString("Settings_LevelFull", resourceCulture); }
        }

        public static string Settings_LevelHigh {
            get { return ResourceManager.GetString("Settings_LevelHigh", resourceCulture); }
        }

        public static string Settings_LevelLow {
            get { return ResourceManager.GetString("Settings_LevelLow", resourceCulture); }
        }

        public static string Settings_LevelNormal {
            get { return ResourceManager.GetString("Settings_LevelNormal", resourceCulture); }
        }

        public static string Settings_PowerAndBattery {
            get { return ResourceManager.GetString("Settings_PowerAndBattery", resourceCulture); }
        }

        public static string Settings_PowerAndBatteryDescription {
            get { return ResourceManager.GetString("Settings_PowerAndBatteryDescription", resourceCulture); }
        }

        public static string Settings_Refresh {
            get { return ResourceManager.GetString("Settings_Refresh", resourceCulture); }
        }

        public static string Settings_RefreshDescription {
            get { return ResourceManager.GetString("Settings_RefreshDescription", resourceCulture); }
        }

        public static string Settings_RefreshSecondsFormat {
            get { return ResourceManager.GetString("Settings_RefreshSecondsFormat", resourceCulture); }
        }

        public static string Settings_ResetAll {
            get { return ResourceManager.GetString("Settings_ResetAll", resourceCulture); }
        }

        public static string Settings_ResetDialogCancel {
            get { return ResourceManager.GetString("Settings_ResetDialogCancel", resourceCulture); }
        }

        public static string Settings_ResetDialogContent {
            get { return ResourceManager.GetString("Settings_ResetDialogContent", resourceCulture); }
        }

        public static string Settings_ResetDialogReset {
            get { return ResourceManager.GetString("Settings_ResetDialogReset", resourceCulture); }
        }

        public static string Settings_ResetDialogTitle {
            get { return ResourceManager.GetString("Settings_ResetDialogTitle", resourceCulture); }
        }

        public static string Settings_ShutDownWithoutConfirmation {
            get { return ResourceManager.GetString("Settings_ShutDownWithoutConfirmation", resourceCulture); }
        }

        public static string Settings_ShutDownWithoutConfirmationDescription {
            get { return ResourceManager.GetString("Settings_ShutDownWithoutConfirmationDescription", resourceCulture); }
        }

        public static string Settings_TrayIconColour {
            get { return ResourceManager.GetString("Settings_TrayIconColour", resourceCulture); }
        }

        public static string Settings_TrayIconColourDescription {
            get { return ResourceManager.GetString("Settings_TrayIconColourDescription", resourceCulture); }
        }

        public static string Settings_TrayIconBackgroundColour {
            get { return ResourceManager.GetString("Settings_TrayIconBackgroundColour", resourceCulture); }
        }

        public static string Settings_TrayIconBackgroundColourDescription {
            get { return ResourceManager.GetString("Settings_TrayIconBackgroundColourDescription", resourceCulture); }
        }

        public static string Settings_TrayIconFont {
            get { return ResourceManager.GetString("Settings_TrayIconFont", resourceCulture); }
        }

        public static string Settings_TrayIconFontDescription {
            get { return ResourceManager.GetString("Settings_TrayIconFontDescription", resourceCulture); }
        }

        public static string Shutdown_DialogAlwaysYes {
            get { return ResourceManager.GetString("Shutdown_DialogAlwaysYes", resourceCulture); }
        }

        public static string Shutdown_DialogContent {
            get { return ResourceManager.GetString("Shutdown_DialogContent", resourceCulture); }
        }

        public static string Shutdown_DialogNo {
            get { return ResourceManager.GetString("Shutdown_DialogNo", resourceCulture); }
        }

        public static string Shutdown_DialogTitle {
            get { return ResourceManager.GetString("Shutdown_DialogTitle", resourceCulture); }
        }

        public static string Shutdown_DialogYes {
            get { return ResourceManager.GetString("Shutdown_DialogYes", resourceCulture); }
        }

        public static string Toast_ButtonDetails {
            get { return ResourceManager.GetString("Toast_ButtonDetails", resourceCulture); }
        }

        public static string Toast_ButtonDisable {
            get { return ResourceManager.GetString("Toast_ButtonDisable", resourceCulture); }
        }

        public static string Tray_AboutHeader {
            get { return ResourceManager.GetString("Tray_AboutHeader", resourceCulture); }
        }

        public static string Tray_AboutTooltip {
            get { return ResourceManager.GetString("Tray_AboutTooltip", resourceCulture); }
        }

        public static string Tray_AppSettingsHeader {
            get { return ResourceManager.GetString("Tray_AppSettingsHeader", resourceCulture); }
        }

        public static string Tray_AppSettingsTooltip {
            get { return ResourceManager.GetString("Tray_AppSettingsTooltip", resourceCulture); }
        }

        public static string Tray_ChargingBodyEta {
            get { return ResourceManager.GetString("Tray_ChargingBodyEta", resourceCulture); }
        }

        public static string Tray_ChargingTitle {
            get { return ResourceManager.GetString("Tray_ChargingTitle", resourceCulture); }
        }

        public static string Tray_DetailsHeader {
            get { return ResourceManager.GetString("Tray_DetailsHeader", resourceCulture); }
        }

        public static string Tray_DetailsTooltip {
            get { return ResourceManager.GetString("Tray_DetailsTooltip", resourceCulture); }
        }

        public static string Tray_DischargingBodyTimeRemaining {
            get { return ResourceManager.GetString("Tray_DischargingBodyTimeRemaining", resourceCulture); }
        }

        public static string Tray_DischargingTitleOnBattery {
            get { return ResourceManager.GetString("Tray_DischargingTitleOnBattery", resourceCulture); }
        }

        public static string Tray_DischargingTitlePlugged {
            get { return ResourceManager.GetString("Tray_DischargingTitlePlugged", resourceCulture); }
        }

        public static string Tray_ExitHeader {
            get { return ResourceManager.GetString("Tray_ExitHeader", resourceCulture); }
        }

        public static string Tray_ExitTooltip {
            get { return ResourceManager.GetString("Tray_ExitTooltip", resourceCulture); }
        }

        public static string Tray_FullyChargedAndPluggedTitle {
            get { return ResourceManager.GetString("Tray_FullyChargedAndPluggedTitle", resourceCulture); }
        }

        public static string Tray_FullyChargedAndPluggedTooltip {
            get { return ResourceManager.GetString("Tray_FullyChargedAndPluggedTooltip", resourceCulture); }
        }

        public static string Tray_FullyChargedTitle {
            get { return ResourceManager.GetString("Tray_FullyChargedTitle", resourceCulture); }
        }

        public static string Tray_FullyChargedTooltip {
            get { return ResourceManager.GetString("Tray_FullyChargedTooltip", resourceCulture); }
        }

        public static string Tray_NoBattery {
            get { return ResourceManager.GetString("Tray_NoBattery", resourceCulture); }
        }

        public static string Tray_PowerSettingsHeader {
            get { return ResourceManager.GetString("Tray_PowerSettingsHeader", resourceCulture); }
        }

        public static string Tray_PowerSettingsTooltip {
            get { return ResourceManager.GetString("Tray_PowerSettingsTooltip", resourceCulture); }
        }

        public static string Tray_ShutDownHeader {
            get { return ResourceManager.GetString("Tray_ShutDownHeader", resourceCulture); }
        }

        public static string Tray_ShutDownTooltip {
            get { return ResourceManager.GetString("Tray_ShutDownTooltip", resourceCulture); }
        }

        public static string Tray_SleepHeader {
            get { return ResourceManager.GetString("Tray_SleepHeader", resourceCulture); }
        }

        public static string Tray_SleepTooltip {
            get { return ResourceManager.GetString("Tray_SleepTooltip", resourceCulture); }
        }
    }
}
