//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Percentage.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Percentage.App.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App info.
        /// </summary>
        public static string About_AppInfo {
            get {
                return ResourceManager.GetString("About_AppInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy full error details.
        /// </summary>
        public static string About_CopyErrorTooltip {
            get {
                return ResourceManager.GetString("About_CopyErrorTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string Copy_Tooltip {
            get {
                return ResourceManager.GetString("Copy_Tooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing to copy.
        /// </summary>
        public static string Copy_NothingToCopyTitle {
            get {
                return ResourceManager.GetString("Copy_NothingToCopyTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was nothing to copy to the clipboard.
        /// </summary>
        public static string Copy_NothingToCopyBody {
            get {
                return ResourceManager.GetString("Copy_NothingToCopyBody", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        public static string Copy_CopiedTitle {
            get {
                return ResourceManager.GetString("Copy_CopiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub issues page.
        /// </summary>
        public static string About_ErrorLinkText {
            get {
                return ResourceManager.GetString("About_ErrorLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can help to fix this by copying the error and report it at the.
        /// </summary>
        public static string About_ErrorMessageBefore {
            get {
                return ResourceManager.GetString("About_ErrorMessageBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has run into an error.
        /// </summary>
        public static string About_ErrorTitle {
            get {
                return ResourceManager.GetString("About_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string About_LinkGitHub {
            get {
                return ResourceManager.GetString("About_LinkGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string About_LinkPayPal {
            get {
                return ResourceManager.GetString("About_LinkPayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app.
        /// </summary>
        public static string About_RateApp {
            get {
                return ResourceManager.GetString("About_RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an issue.
        /// </summary>
        public static string About_ReportIssue {
            get {
                return ResourceManager.GetString("About_ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code.
        /// </summary>
        public static string About_SourceCode {
            get {
                return ResourceManager.GetString("About_SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support my work.
        /// </summary>
        public static string About_SupportMyWork {
            get {
                return ResourceManager.GetString("About_SupportMyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Percentage Icon version {0} has run into an error. You can help to fix this by:
        ///1. Press Ctrl+C on this message
        ///2. Report the copied error at https://github.com/soleon/Percentage/issues
        ///
        ///{1}.
        /// </summary>
        public static string App_GeneralErrorBody {
            get {
                return ResourceManager.GetString("App_GeneralErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Found An Error.
        /// </summary>
        public static string App_GeneralErrorTitle {
            get {
                return ResourceManager.GetString("App_GeneralErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Percentage Icon version {0} did not have enough memory to perform some work.
        ///Please consider closing some running applications or background services to free up some memory..
        /// </summary>
        public static string App_OutOfMemoryBody {
            get {
                return ResourceManager.GetString("App_OutOfMemoryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your system memory is running low.
        /// </summary>
        public static string App_OutOfMemoryTitle {
            get {
                return ResourceManager.GetString("App_OutOfMemoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime architecture.
        /// </summary>
        public static string AppInfo_RuntimeArchitecture {
            get {
                return ResourceManager.GetString("AppInfo_RuntimeArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime version.
        /// </summary>
        public static string AppInfo_RuntimeVersion {
            get {
                return ResourceManager.GetString("AppInfo_RuntimeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version.
        /// </summary>
        public static string AppInfo_Version {
            get {
                return ResourceManager.GetString("AppInfo_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Capacity.
        /// </summary>
        public static string Battery_Capacity {
            get {
                return ResourceManager.GetString("Battery_Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Rate.
        /// </summary>
        public static string Battery_ChargeRate {
            get {
                return ResourceManager.GetString("Battery_ChargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Capacity.
        /// </summary>
        public static string Battery_DesignCapacity {
            get {
                return ResourceManager.GetString("Battery_DesignCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Charge Capacity.
        /// </summary>
        public static string Battery_FullChargeCapacity {
            get {
                return ResourceManager.GetString("Battery_FullChargeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Health.
        /// </summary>
        public static string Battery_Health {
            get {
                return ResourceManager.GetString("Battery_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Line Status.
        /// </summary>
        public static string Battery_PowerLineStatus {
            get {
                return ResourceManager.GetString("Battery_PowerLineStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Charge Capacity.
        /// </summary>
        public static string Battery_RemainingChargeCapacity {
            get {
                return ResourceManager.GetString("Battery_RemainingChargeCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Status.
        /// </summary>
        public static string Battery_Status {
            get {
                return ResourceManager.GetString("Battery_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Time.
        /// </summary>
        public static string Battery_Time {
            get {
                return ResourceManager.GetString("Battery_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remaining.
        /// </summary>
        public static string Battery_TimeRemaining {
            get {
                return ResourceManager.GetString("Battery_TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} until full.
        /// </summary>
        public static string Battery_TimeUntilFull {
            get {
                return ResourceManager.GetString("Battery_TimeUntilFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Battery_ValueConnected {
            get {
                return ResourceManager.GetString("Battery_ValueConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Battery_ValueDisconnected {
            get {
                return ResourceManager.GetString("Battery_ValueDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Charging.
        /// </summary>
        public static string Battery_ValueNotCharging {
            get {
                return ResourceManager.GetString("Battery_ValueNotCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Battery_ValueUnknown {
            get {
                return ResourceManager.GetString("Battery_ValueUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Details_CopyButton {
            get {
                return ResourceManager.GetString("Details_CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details_PageTitle {
            get {
                return ResourceManager.GetString("Details_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Details_RefreshButton {
            get {
                return ResourceManager.GetString("Details_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Percentage Icon.
        /// </summary>
        public static string Main_WindowTitle {
            get {
                return ResourceManager.GetString("Main_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Nav_About {
            get {
                return ResourceManager.GetString("Nav_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Nav_Details {
            get {
                return ResourceManager.GetString("Nav_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string Readable_HourPlural {
            get {
                return ResourceManager.GetString("Readable_HourPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string Readable_HourSingular {
            get {
                return ResourceManager.GetString("Readable_HourSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less than 1 minute.
        /// </summary>
        public static string Readable_LessThanOneMinute {
            get {
                return ResourceManager.GetString("Readable_LessThanOneMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string Readable_MinutePlural {
            get {
                return ResourceManager.GetString("Readable_MinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string Readable_MinuteSingular {
            get {
                return ResourceManager.GetString("Readable_MinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Settings_AutoColour {
            get {
                return ResourceManager.GetString("Settings_AutoColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system text colour.
        /// </summary>
        public static string Settings_AutoColourTooltip {
            get {
                return ResourceManager.GetString("Settings_AutoColourTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start.
        /// </summary>
        public static string Settings_AutoStart {
            get {
                return ResourceManager.GetString("Settings_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the application when Windows starts up.
        /// </summary>
        public static string Settings_AutoStartDescription {
            get {
                return ResourceManager.GetString("Settings_AutoStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start for this app has been disabled manually by system policy.
        ///
        ///To re-enable it, remove any system policies that restrict auto start, and go to &quot;Settings &gt; Apps &gt; Startup&quot; to enable &quot;Battery Percentage Icon&quot;..
        /// </summary>
        public static string Settings_AutoStartDisabledByPolicyDialogContent {
            get {
                return ResourceManager.GetString("Settings_AutoStartDisabledByPolicyDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start disabled by policy.
        /// </summary>
        public static string Settings_AutoStartDisabledByPolicyDialogTitle {
            get {
                return ResourceManager.GetString("Settings_AutoStartDisabledByPolicyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start for this app has been disabled manually in system settings.
        ///
        ///To re-enable it, please go to &quot;Settings &gt; Apps &gt; Startup&quot; to enable &quot;Battery Percentage Icon&quot;..
        /// </summary>
        public static string Settings_AutoStartDisabledByUserDialogContent {
            get {
                return ResourceManager.GetString("Settings_AutoStartDisabledByUserDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start disabled by user.
        /// </summary>
        public static string Settings_AutoStartDisabledByUserDialogTitle {
            get {
                return ResourceManager.GetString("Settings_AutoStartDisabledByUserDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start for this app has been disabled.
        ///
        ///To re-enable it, please go to &quot;Settings &gt; Apps &gt; Startup&quot; to enable &quot;Battery Percentage Icon&quot;..
        /// </summary>
        public static string Settings_AutoStartDisabledDialogContent {
            get {
                return ResourceManager.GetString("Settings_AutoStartDisabledDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start disabled.
        /// </summary>
        public static string Settings_AutoStartDisabledDialogTitle {
            get {
                return ResourceManager.GetString("Settings_AutoStartDisabledDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start requires this app to run as a Windows Store app..
        /// </summary>
        public static string Settings_AutoStartDisabledMessage {
            get {
                return ResourceManager.GetString("Settings_AutoStartDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start Disabled.
        /// </summary>
        public static string Settings_AutoStartDisabledTitle {
            get {
                return ResourceManager.GetString("Settings_AutoStartDisabledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery levels &amp; notifications.
        /// </summary>
        public static string Settings_BatteryLevelsAndNotifications {
            get {
                return ResourceManager.GetString("Settings_BatteryLevelsAndNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change notifications for different battery levels.
        /// </summary>
        public static string Settings_BatteryLevelsAndNotificationsDescription {
            get {
                return ResourceManager.GetString("Settings_BatteryLevelsAndNotificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click activation.
        /// </summary>
        public static string Settings_DoubleClickActivation {
            get {
                return ResourceManager.GetString("Settings_DoubleClickActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click the tray icon to show battery details.
        /// </summary>
        public static string Settings_DoubleClickActivationDescription {
            get {
                return ResourceManager.GetString("Settings_DoubleClickActivationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Settings_FontSize {
            get {
                return ResourceManager.GetString("Settings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide at startup.
        /// </summary>
        public static string Settings_HideAtStartup {
            get {
                return ResourceManager.GetString("Settings_HideAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the main window when the application starts up.
        /// </summary>
        public static string Settings_HideAtStartupDescription {
            get {
                return ResourceManager.GetString("Settings_HideAtStartupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the language used by this app.
        /// </summary>
        public static string Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("Settings_LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_LanguageHeader {
            get {
                return ResourceManager.GetString("Settings_LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use system language.
        /// </summary>
        public static string Settings_LanguageSystem {
            get {
                return ResourceManager.GetString("Settings_LanguageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        public static string Settings_LevelCharging {
            get {
                return ResourceManager.GetString("Settings_LevelCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Settings_LevelCritical {
            get {
                return ResourceManager.GetString("Settings_LevelCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Settings_LevelFull {
            get {
                return ResourceManager.GetString("Settings_LevelFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Settings_LevelHigh {
            get {
                return ResourceManager.GetString("Settings_LevelHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Settings_LevelLow {
            get {
                return ResourceManager.GetString("Settings_LevelLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Settings_LevelNormal {
            get {
                return ResourceManager.GetString("Settings_LevelNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power &amp; battery.
        /// </summary>
        public static string Settings_PowerAndBattery {
            get {
                return ResourceManager.GetString("Settings_PowerAndBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open system power and battery settings.
        /// </summary>
        public static string Settings_PowerAndBatteryDescription {
            get {
                return ResourceManager.GetString("Settings_PowerAndBatteryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Settings_Refresh {
            get {
                return ResourceManager.GetString("Settings_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How frequent the battery status is refreshed.
        /// </summary>
        public static string Settings_RefreshDescription {
            get {
                return ResourceManager.GetString("Settings_RefreshDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds.
        /// </summary>
        public static string Settings_RefreshSecondsFormat {
            get {
                return ResourceManager.GetString("Settings_RefreshSecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Settings.
        /// </summary>
        public static string Settings_ResetAll {
            get {
                return ResourceManager.GetString("Settings_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Settings_ResetDialogCancel {
            get {
                return ResourceManager.GetString("Settings_ResetDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings to their default values?.
        /// </summary>
        public static string Settings_ResetDialogContent {
            get {
                return ResourceManager.GetString("Settings_ResetDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Settings_ResetDialogReset {
            get {
                return ResourceManager.GetString("Settings_ResetDialogReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Settings.
        /// </summary>
        public static string Settings_ResetDialogTitle {
            get {
                return ResourceManager.GetString("Settings_ResetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down without confirmation.
        /// </summary>
        public static string Settings_ShutDownWithoutConfirmation {
            get {
                return ResourceManager.GetString("Settings_ShutDownWithoutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not show confirmation when shutting down your device.
        /// </summary>
        public static string Settings_ShutDownWithoutConfirmationDescription {
            get {
                return ResourceManager.GetString("Settings_ShutDownWithoutConfirmationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon background colour.
        /// </summary>
        public static string Settings_TrayIconBackgroundColour {
            get {
                return ResourceManager.GetString("Settings_TrayIconBackgroundColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tray icon background colour for different battery levels.
        /// </summary>
        public static string Settings_TrayIconBackgroundColourDescription {
            get {
                return ResourceManager.GetString("Settings_TrayIconBackgroundColourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon colour.
        /// </summary>
        public static string Settings_TrayIconColour {
            get {
                return ResourceManager.GetString("Settings_TrayIconColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tray icon colour for different battery levels.
        /// </summary>
        public static string Settings_TrayIconColourDescription {
            get {
                return ResourceManager.GetString("Settings_TrayIconColourDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray icon font.
        /// </summary>
        public static string Settings_TrayIconFont {
            get {
                return ResourceManager.GetString("Settings_TrayIconFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change tray icon font, size and style.
        /// </summary>
        public static string Settings_TrayIconFontDescription {
            get {
                return ResourceManager.GetString("Settings_TrayIconFontDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Yes.
        /// </summary>
        public static string Shutdown_DialogAlwaysYes {
            get {
                return ResourceManager.GetString("Shutdown_DialogAlwaysYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to shut down your device?.
        /// </summary>
        public static string Shutdown_DialogContent {
            get {
                return ResourceManager.GetString("Shutdown_DialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Shutdown_DialogNo {
            get {
                return ResourceManager.GetString("Shutdown_DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut Down.
        /// </summary>
        public static string Shutdown_DialogTitle {
            get {
                return ResourceManager.GetString("Shutdown_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Shutdown_DialogYes {
            get {
                return ResourceManager.GetString("Shutdown_DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Toast_ButtonDetails {
            get {
                return ResourceManager.GetString("Toast_ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Toast_ButtonDisable {
            get {
                return ResourceManager.GetString("Toast_ButtonDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string Tray_AboutHeader {
            get {
                return ResourceManager.GetString("Tray_AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show application information.
        /// </summary>
        public static string Tray_AboutTooltip {
            get {
                return ResourceManager.GetString("Tray_AboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App _settings.
        /// </summary>
        public static string Tray_AppSettingsHeader {
            get {
                return ResourceManager.GetString("Tray_AppSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open application settings.
        /// </summary>
        public static string Tray_AppSettingsTooltip {
            get {
                return ResourceManager.GetString("Tray_AppSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} until fully charged.
        /// </summary>
        public static string Tray_ChargingBodyEta {
            get {
                return ResourceManager.GetString("Tray_ChargingBodyEta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% charging.
        /// </summary>
        public static string Tray_ChargingTitle {
            get {
                return ResourceManager.GetString("Tray_ChargingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Details.
        /// </summary>
        public static string Tray_DetailsHeader {
            get {
                return ResourceManager.GetString("Tray_DetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show battery details.
        /// </summary>
        public static string Tray_DetailsTooltip {
            get {
                return ResourceManager.GetString("Tray_DetailsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} remaining.
        /// </summary>
        public static string Tray_DischargingBodyTimeRemaining {
            get {
                return ResourceManager.GetString("Tray_DischargingBodyTimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% on battery.
        /// </summary>
        public static string Tray_DischargingTitleOnBattery {
            get {
                return ResourceManager.GetString("Tray_DischargingTitleOnBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% connected (not charging).
        /// </summary>
        public static string Tray_DischargingTitlePlugged {
            get {
                return ResourceManager.GetString("Tray_DischargingTitlePlugged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string Tray_ExitHeader {
            get {
                return ResourceManager.GetString("Tray_ExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application.
        /// </summary>
        public static string Tray_ExitTooltip {
            get {
                return ResourceManager.GetString("Tray_ExitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully charged and connected to power.
        /// </summary>
        public static string Tray_FullyChargedAndPluggedTitle {
            get {
                return ResourceManager.GetString("Tray_FullyChargedAndPluggedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your battery is fully charged and connected to power.
        /// </summary>
        public static string Tray_FullyChargedAndPluggedTooltip {
            get {
                return ResourceManager.GetString("Tray_FullyChargedAndPluggedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully charged.
        /// </summary>
        public static string Tray_FullyChargedTitle {
            get {
                return ResourceManager.GetString("Tray_FullyChargedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your battery is fully charged.
        /// </summary>
        public static string Tray_FullyChargedTooltip {
            get {
                return ResourceManager.GetString("Tray_FullyChargedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No battery detected.
        /// </summary>
        public static string Tray_NoBattery {
            get {
                return ResourceManager.GetString("Tray_NoBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Power &amp; battery settings.
        /// </summary>
        public static string Tray_PowerSettingsHeader {
            get {
                return ResourceManager.GetString("Tray_PowerSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Windows system power and battery settings.
        /// </summary>
        public static string Tray_PowerSettingsTooltip {
            get {
                return ResourceManager.GetString("Tray_PowerSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sh_ut down device.
        /// </summary>
        public static string Tray_ShutDownHeader {
            get {
                return ResourceManager.GetString("Tray_ShutDownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shut down your device.
        /// </summary>
        public static string Tray_ShutDownTooltip {
            get {
                return ResourceManager.GetString("Tray_ShutDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Sleep device.
        /// </summary>
        public static string Tray_SleepHeader {
            get {
                return ResourceManager.GetString("Tray_SleepHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn your device to sleep mode.
        /// </summary>
        public static string Tray_SleepTooltip {
            get {
                return ResourceManager.GetString("Tray_SleepTooltip", resourceCulture);
            }
        }
    }
}
