//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Percentage.App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BatteryCriticalNotification {
            get {
                return ((bool)(this["BatteryCriticalNotification"]));
            }
            set {
                this["BatteryCriticalNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BatteryLowNotification {
            get {
                return ((bool)(this["BatteryLowNotification"]));
            }
            set {
                this["BatteryLowNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BatteryHighNotification {
            get {
                return ((bool)(this["BatteryHighNotification"]));
            }
            set {
                this["BatteryHighNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BatteryFullNotification {
            get {
                return ((bool)(this["BatteryFullNotification"]));
            }
            set {
                this["BatteryFullNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int BatteryHighNotificationValue {
            get {
                return ((int)(this["BatteryHighNotificationValue"]));
            }
            set {
                this["BatteryHighNotificationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int RefreshSeconds {
            get {
                return ((int)(this["RefreshSeconds"]));
            }
            set {
                this["RefreshSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int BatteryLowNotificationValue {
            get {
                return ((int)(this["BatteryLowNotificationValue"]));
            }
            set {
                this["BatteryLowNotificationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int BatteryCriticalNotificationValue {
            get {
                return ((int)(this["BatteryCriticalNotificationValue"]));
            }
            set {
                this["BatteryCriticalNotificationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E81123")]
        public string BatteryCriticalColour {
            get {
                return ((string)(this["BatteryCriticalColour"]));
            }
            set {
                this["BatteryCriticalColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CA5010")]
        public string BatteryLowColour {
            get {
                return ((string)(this["BatteryLowColour"]));
            }
            set {
                this["BatteryLowColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#10893E")]
        public string BatteryChargingColour {
            get {
                return ((string)(this["BatteryChargingColour"]));
            }
            set {
                this["BatteryChargingColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BatteryNormalColour {
            get {
                return ((string)(this["BatteryNormalColour"]));
            }
            set {
                this["BatteryNormalColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HideAtStartup {
            get {
                return ((bool)(this["HideAtStartup"]));
            }
            set {
                this["HideAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif")]
        public global::System.Windows.Media.FontFamily TrayIconFontFamily {
            get {
                return ((global::System.Windows.Media.FontFamily)(this["TrayIconFontFamily"]));
            }
            set {
                this["TrayIconFontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrayIconFontBold {
            get {
                return ((bool)(this["TrayIconFontBold"]));
            }
            set {
                this["TrayIconFontBold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TrayIconFontUnderline {
            get {
                return ((bool)(this["TrayIconFontUnderline"]));
            }
            set {
                this["TrayIconFontUnderline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsAutoBatteryNormalColour {
            get {
                return ((bool)(this["IsAutoBatteryNormalColour"]));
            }
            set {
                this["IsAutoBatteryNormalColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoBatteryLowColour {
            get {
                return ((bool)(this["IsAutoBatteryLowColour"]));
            }
            set {
                this["IsAutoBatteryLowColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoBatteryChargingColour {
            get {
                return ((bool)(this["IsAutoBatteryChargingColour"]));
            }
            set {
                this["IsAutoBatteryChargingColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoBatteryCriticalColour {
            get {
                return ((bool)(this["IsAutoBatteryCriticalColour"]));
            }
            set {
                this["IsAutoBatteryCriticalColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double TrayIconFontSize {
            get {
                return ((double)(this["TrayIconFontSize"]));
            }
            set {
                this["TrayIconFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoubleClickActivation {
            get {
                return ((bool)(this["DoubleClickActivation"]));
            }
            set {
                this["DoubleClickActivation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShutDownWithoutConfirmation {
            get {
                return ((bool)(this["ShutDownWithoutConfirmation"]));
            }
            set {
                this["ShutDownWithoutConfirmation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RequiresUpgrade {
            get {
                return ((bool)(this["RequiresUpgrade"]));
            }
            set {
                this["RequiresUpgrade"] = value;
            }
        }
    }
}
